/**
 ******************************************************************************
 * @file    main.c
 * @brief   EV ADAS Dashboard - application entry point.
 *
 * Target       : STM32F103C8T6 (Blue Pill), 72 MHz (HSE 8MHz x9 PLL)
 * Simulator    : PICSimLab
 *
 * IMPORTANT - How to use this file
 * ---------------------------------
 * This file assumes you generated the peripheral drivers with STM32CubeMX
 * using the pin/peripheral configuration described in the project README
 * (ADC1 on PA0-PA3, USART1 on PA9/PA10, TIM2 as a free-running 1 MHz time
 * base, GPIO outputs on PB0/PB2/PB4 + PB8-PB11, GPIO inputs on PB1/PB3/PB5).
 * Replace the CubeMX-generated Core/Src/main.c with this file (it already
 * contains SystemClock_Config + Error_Handler in the standard CubeMX style)
 * and keep the CubeMX-generated MX_xxx_Init() implementations further down
 * in this same file, OR leave them in the files CubeMX put them in and just
 * make sure the prototypes below match.
 ******************************************************************************
 */
#include "common.h"
#include "ev_control.h"
#include "adas.h"
#include "ultrasonic.h"
#include "fault.h"
#include "uart_shell.h"

/* ---------------------------------------------------------------------- */
/* Peripheral handles (generated by CubeMX)                               */
/* ---------------------------------------------------------------------- */
ADC_HandleTypeDef  hadc1;
UART_HandleTypeDef huart1;
TIM_HandleTypeDef  htim2;

/* ---------------------------------------------------------------------- */
/* Sensor pin table (must match README pin mapping)                       */
/* ---------------------------------------------------------------------- */
static const Ultrasonic_Sensor_t SENSOR_FRONT = { GPIOB, GPIO_PIN_0, GPIOB, GPIO_PIN_1 };
static const Ultrasonic_Sensor_t SENSOR_LEFT  = { GPIOB, GPIO_PIN_2, GPIOB, GPIO_PIN_3 };
static const Ultrasonic_Sensor_t SENSOR_RIGHT = { GPIOB, GPIO_PIN_4, GPIOB, GPIO_PIN_5 };

/* ---------------------------------------------------------------------- */
/* Prototypes                                                              */
/* ---------------------------------------------------------------------- */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_TIM2_Init(void);
void Error_Handler(void);

/* ---------------------------------------------------------------------- */
int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_USART1_UART_Init();
    MX_TIM2_Init();

    /* ---- Application module init ------------------------------------ */
    EV_Init(&hadc1);
    ADAS_Init();
    Fault_Init();
    Ultrasonic_Init(&htim2);
    Shell_Init(&huart1);

    uint32_t last_tick = HAL_GetTick();

    while (1)
    {
        /* Service any pending UART shell command every loop iteration    */
        Shell_Poll();

        uint32_t now = HAL_GetTick();
        if ((now - last_tick) >= CONTROL_PERIOD_MS)
        {
            float dt_s = (now - last_tick) / 1000.0f;
            last_tick = now;

            /* ---- 1. Read the 3 ultrasonic sensors (blocking, ~us) --- */
            float front_cm = Ultrasonic_ReadCM(&SENSOR_FRONT);
            float left_cm  = Ultrasonic_ReadCM(&SENSOR_LEFT);
            float right_cm = Ultrasonic_ReadCM(&SENSOR_RIGHT);

            /* ---- 2. Update vehicle physics + ADAS + faults ---------- */
            EV_Update(dt_s);
            const EV_State_t *ev = EV_GetState();

            ADAS_Update(front_cm, left_cm, right_cm, ev->speed_kmh);
            const ADAS_State_t *adas = ADAS_GetState();

            Fault_Update(ev->motor_temp_c, ev->soc_pct, adas->collision, adas);

            /* ---- 3. Stream telemetry over UART @ 10 Hz -------------- */
            Shell_SendTelemetry(ev, adas, Fault_GetByte());
        }
    }
}

/* ---------------------------------------------------------------------- */
/* HAL callback: forward every completed UART byte RX to the shell module */
/* ---------------------------------------------------------------------- */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    Shell_RxCallback(huart);
}

/* ---------------------------------------------------------------------- */
/* Clock config: HSE 8 MHz -> PLL x9 -> 72 MHz SYSCLK (standard Blue Pill) */
/* ---------------------------------------------------------------------- */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) Error_Handler();

    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) Error_Handler();
}

/* ---------------------------------------------------------------------- */
/* GPIO: PB0/PB2/PB4 = TRIG outputs, PB1/PB3/PB5 = ECHO inputs,            */
/*       PB8-PB11 = status LED outputs                                    */
/* ---------------------------------------------------------------------- */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_AFIO_CLK_ENABLE();

    /* TRIG outputs: PB0, PB2, PB4 */
    GPIO_InitStruct.Pin = GPIO_PIN_0 | GPIO_PIN_2 | GPIO_PIN_4;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* ECHO inputs: PB1, PB3, PB5 */
    GPIO_InitStruct.Pin = GPIO_PIN_1 | GPIO_PIN_3 | GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* Status LEDs: PB8-PB11 */
    GPIO_InitStruct.Pin = GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0 | GPIO_PIN_2 | GPIO_PIN_4, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_11, GPIO_PIN_RESET);
}

/* ---------------------------------------------------------------------- */
/* ADC1: PA0-PA3 as analog inputs, single-conversion, software triggered  */
/* ---------------------------------------------------------------------- */
static void MX_ADC1_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_ADC1_CLK_ENABLE();
    __HAL_RCC_ADC_CONFIG(RCC_ADCPCLK2_DIV6);   /* 72MHz/6 = 12MHz, within 14MHz max spec */

    GPIO_InitStruct.Pin = GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3;
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    hadc1.Instance = ADC1;
        hadc1.Init.ScanConvMode = ADC_SCAN_ENABLE;     // was DISABLE
        hadc1.Init.ContinuousConvMode = DISABLE;
        hadc1.Init.DiscontinuousConvMode = DISABLE;
        hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
        hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
        hadc1.Init.NbrOfConversion = 4;                // was 1
        if (HAL_ADC_Init(&hadc1) != HAL_OK) Error_Handler();

        ADC_ChannelConfTypeDef sConfig = {0};
        sConfig.SamplingTime = ADC_SAMPLETIME_55CYCLES_5;

        sConfig.Channel = ADC_CHANNEL_0; sConfig.Rank = 1; HAL_ADC_ConfigChannel(&hadc1, &sConfig);
        sConfig.Channel = ADC_CHANNEL_1; sConfig.Rank = 2; HAL_ADC_ConfigChannel(&hadc1, &sConfig);
        sConfig.Channel = ADC_CHANNEL_2; sConfig.Rank = 3; HAL_ADC_ConfigChannel(&hadc1, &sConfig);
        sConfig.Channel = ADC_CHANNEL_3; sConfig.Rank = 4; HAL_ADC_ConfigChannel(&hadc1, &sConfig);
}

/* ---------------------------------------------------------------------- */
/* USART1 @ 115200 8N1, PA9 = TX, PA10 = RX, RX interrupt enabled          */
/* ---------------------------------------------------------------------- */
static void MX_USART1_UART_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_USART1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA9 = TX, alternate function push-pull */
    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* PA10 = RX, floating input */
    GPIO_InitStruct.Pin = GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    huart1.Instance = USART1;
    huart1.Init.BaudRate = 115200;
    huart1.Init.WordLength = UART_WORDLENGTH_8B;
    huart1.Init.StopBits = UART_STOPBITS_1;
    huart1.Init.Parity = UART_PARITY_NONE;
    huart1.Init.Mode = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart1) != HAL_OK) Error_Handler();

    HAL_NVIC_SetPriority(USART1_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(USART1_IRQn);
}

/* ---------------------------------------------------------------------- */
/* TIM2: free-running 1 MHz (1 us/tick) time base for ultrasonic timing    */
/* ---------------------------------------------------------------------- */
static void MX_TIM2_Init(void)
{
    __HAL_RCC_TIM2_CLK_ENABLE();

    htim2.Instance = TIM2;
    htim2.Init.Prescaler = (uint32_t)(SystemCoreClock / 1000000U) - 1U; /* -> 1 MHz */
    htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
    htim2.Init.Period = 0xFFFF;
    htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    if (HAL_TIM_Base_Init(&htim2) != HAL_OK) Error_Handler();

    HAL_TIM_Base_Start(&htim2);   /* starts the free-running counter */
}

/* ---------------------------------------------------------------------- */
void Error_Handler(void)
{
    __disable_irq();
    while (1) { /* trap - check clock config / peripheral init */ }
}

#ifdef  USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line) { /* user-implementable */ }
#endif
